"""add google_calendar_event_id to sickness_declarations

Revision ID: 5af70045bede
Revises: b2e550034736
Create Date: 2025-08-18 14:10:12.672130

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5af70045bede'
down_revision: Union[str, None] = 'b2e550034736'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sickness_declarations', sa.Column('google_calendar_event_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sickness_declarations', 'google_calendar_event_id')
    # ### end Alembic commands ###
