"""Add google_calendar_event_id to absence_requests

Revision ID: 7bc882c65142
Revises: 
Create Date: 2025-08-05 23:32:02.565332

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7bc882c65142'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('absence_requests', sa.Column('google_calendar_event_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('absence_requests', 'google_calendar_event_id')
    # ### end Alembic commands ###
